### ISSUE TITLE
[FEAT] iOS 4차 과제 - Networking

### ISSUE THREAD

**Issue by seondal** [29th-WE-SOPT-iOS-Part/KimSeonYeong#7]
## 📌  Feature Issue

로그인 회원가입에 실제 API붙이기

## 📝  To-do

- [ ] home 화면을 첫 화면으로 설정하기
- [ ] 프로필 눌렀을 때 로그인 flow 로 넘어가게 화면전환 연결하기
- [ ] 로그인 -> 서버에서 넘겨주는 message로 alert 띄우기
- [ ] 회원가입 -> 서버에서 넘겨주는 message로 alert 띄우기
- [ ] UserDefault 활용하여 확인화면에서 화면에 값 띄워주기
