### ISSUE TITLE
[FEAT] iOS 7차 과제 - 데이터 연결 심화, UIGestureRecognizer

### ISSUE THREAD

**Issue by seondal** [29th-WE-SOPT-iOS-Part/KimSeonYeong#9]
## 📌  Feature Issue

1. Image View에 tap gesture recognizer 를 달아서 imageView 가 tap 되었을 때 action을 할 수 있도록 추가
2. ImageView가 tap 되었을 때 옆에 화면으로 present 되도록 화면 전환 (화면전환 시 데이터 전달)

## 📝  To-do

- [ ] ImageView 에 tap gesture recognizer 달기
- [ ] imageView가 tap 되었을 때 action 추가
- [ ] imageView 가 tap 되었을 때 옆의 화면으로 present
- [ ] 화면전환 데이터 전달 ( imageView, 영상 제목, 조회수, 업로드, 시간)
- [ ] dismiss 버튼
